### ISSUE TITLE
[BUG] noVNC encountered an error

### ISSUE THREAD

**Issue by Kurasami** [linuxserver/docker-vscodium#3]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After installing the container, installing 3 extensions, noVNC crashed in the middle of me browsing through folders.

![image](https://github.com/linuxserver/docker-vscodium/assets/77334270/b61437ad-9fce-4e76-bdf4-666cc019cc73)

### Expected Behavior

noVNC shouldn't crash and the container should work fine.

### Steps To Reproduce

1. Install container
2. Install a few extensions
3. Container crashes with the above error

### Environment

```markdown
- OS: Unraid
- How docker service was installed: via Unraid Apps
```

### CPU architecture

x86-64

### Docker creation

```bash
I used Unraid. Just installed via the apps tab.

vscodium
linuxserver
VSCodium(https://vscodium.com/) is a community-driven, freely-licensed binary distribution of Microsoft’s editor VS Code.

Details
Application Type	Docker
Categories	Other
Added	Apr 5, 2023
Downloads	More than 1,000
Repository	lscr.io/linuxserver/vscodium
DockerHub Stars:	4 
Last Update:	Jul 7, 2023
Maintainer
linuxserverRepository IconAll Apps Profile Favourite
Donations
Donate
Change Log
Note: not all maintainers keep up to date on change logs
2023-04-02
Initial release.
    

Template Errors
No category entry present
```

### Container logs

```bash
text  error  warn  system  array  login  

Generating a RSA private key
...+++++
................................................................................................................+++++
writing new private key to '/config/ssl/cert.key'
-----
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.

Xvnc KasmVNC 1.1.0 - built Jul  1 2023 18:56:19
Copyright (C) 1999-2018 KasmVNC Team and many others (see README.me)
See http://kasmweb.com for information on KasmVNC.
Underlying X server release 12014000, The X.Org Foundation


ERROR: openbox-xdg-autostart requires PyXDG to be installed
 2023-07-08 13:33:37,191 [INFO] websocket 0: got client connection from 127.0.0.1
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗ 
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    99
User GID:    100
───────────────────────────────────────

[custom-init] No custom files found, skipping...
[ls.io-init] done.
Obt-Message: Xinerama extension is not present on the server
 2023-07-08 13:33:37,204 [PRIO] Connections: accepted: @192.168.1.77_1688812417.191596::websocket
 2023-07-08 13:38:45,537 [PRIO] Connections: closed: @192.168.1.77_1688812417.191596::websocket (Clean disconnection)
```
```

**Comment by Kurasami** [comment]
It seems to happen when the browser tab goes inactive on Chrome.

So it'll work fine so long as the tab is active. As soon as it becomes inactive I get this error. Refreshing the page fixes the error.

**Comment by j0nnymoe** [comment]
This won't be related to the container. You need to fix chrome to not go inactive on certain websites (if that's even possible.)

**Comment by Kurasami** [comment]
How is this not related to the container? None of my other noVNC containers have this error.

The error message clearly states that it's an issue with an undefined local variable inside the container.

**Comment by Kurasami** [comment]
Update: Exact same issue on Edge and Firefox.

You guys going to just ignore modern browser requirements now huh?

**Comment by j0nnymoe** [comment]
Are you using it behind a reverse proxy?

**Comment by Kurasami** [comment]
No I am connecting to it directly through the browser.

**Comment by Kurasami** [comment]
> ~Are you using it behind a reverse proxy?~
> 
> Infact forget that. Could you screenshot or provide the docker run that unraid provides?

```
docker run
  -d
  --name='vscodium-1-1'
  --net='bridge'
  -e TZ="Europe/Kiev"
  -e HOST_OS="Unraid"
  -e HOST_HOSTNAME="Tower"
  -e HOST_CONTAINERNAME="vscodium-1-1"
  -e 'PUID'='99'
  -e 'PGID'='100'
  -e 'UMASK'='022'
  -l net.unraid.docker.managed=dockerman
  -l net.unraid.docker.webui='http://[IP]:[PORT:3000]'
  -l net.unraid.docker.icon='https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/vscodium-icon.png'
  -p '3000:3000/tcp'
  -p '3001:3001/tcp'
  -v '/mnt/user/appdata/vscodium-1-1':'/config':'rw'
  --cap-add=IPC_LOCK
  --shm-size=1gb 'lscr.io/linuxserver/vscodium'
fede1756d9bf212768daaf8da34f41bb6411792bada28202346345fc4df43459

The command finished successfully!
```

**Comment by j0nnymoe** [comment]
Not sure where you're wanting to cotinue support for this but just tested the container with installing 5 extensions and couldn't get it to trigger, Using firefox: https://i.j0nny.moe/view/XbeEJN.gif

**Comment by Kurasami** [comment]
Here would be the best place.

I'm not sure what differs here except how Unraid installed the container perhaps? There's a few other errors in the log above. Maybe it's related to that? eg. the X11 error?

`_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.`

or

`ERROR: openbox-xdg-autostart requires PyXDG to be installed`

**Comment by j0nnymoe** [comment]
I've also installed the container on my unraid box, all seems to work fine.

**Comment by Kurasami** [comment]
Have you tried it with Chrome? Edge?
If it works with only one of the major browsers, that's not much consolation.

What is wrong with it the way that it is set up by default?
![Screenshot_1](https://github.com/linuxserver/docker-vscodium/assets/77334270/71a49f39-a434-4a3b-8a61-be0065476bab)

How should I reference it then instead of the above?

If you mean having my "data" and container "appdata" folders separately. I generally try to keep user data that I write completely separate from my appdata folder. That is, if I install something and directly add files via its UI, I want those stored away from the appdata folder. The appdata folder after all, is for config files only anyway.

Would you argue that the container should support fuse mountspaces without an issue like this?

**Comment by j0nnymoe** [comment]
Just tested in edge, installed about 10 extensions, randomly browsing around the file system. I was unable to replicate the error.
