### ISSUE TITLE
[FEAT] Add parameter to set host IP

### ISSUE THREAD

**Issue by Ali-Flt** [linuxserver/docker-vscodium#6]
### Is this a new feature request?

- [X] I have searched the existing issues

### Wanted change

A parameter being added to set the host IP address.

### Reason for change

One may want the server to be on localhost instead of 0.0.0.0

**Comment by aptalca** [comment]
Please elaborate and keep the xy problem in mind https://xyproblem.info/

**Comment by Ali-Flt** [comment]
Right now it is possible to change the HTTP and HTTPS port of the service (default is 3000 and 3001).
But I couldn't find an option to change the bind IP address of the service. I think it runs the service on 0.0.0.0 (all network interfaces). A parameter to choose the network interface could be very useful.
This way I can run the VScodium service on 127.0.0.1:3000 instead of 0.0.0.0:3000

**Comment by aptalca** [comment]
Why?

In a docker bridge network, you map the container port to whatever host port you want. You don't need to change the container ports.

You can also map `127.0.0.1:3000:3000` so on the host it only listens at that IP

**Comment by Ali-Flt** [comment]
You are right, I was confused for a sec I forgot I'm publishing the ports from the container to host instead of running the service directly on the host. Closing this.
