### ISSUE TITLE
[BUG] Platformio extension not working without python3-venv

### ISSUE THREAD

**Issue by melwinek** [linuxserver/docker-vscodium#9]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

n/a

### Expected Behavior

Please add python3-venv package.

### Steps To Reproduce

n/a

### Environment

```markdown
- OS:
- How docker service was installed:
```

### CPU architecture

x86-64

### Docker creation

```bash
n/a
```

### Container logs

```bash
n/a
```

**Comment by Roxedus** [comment]
You can install this automatically on startup. https://github.com/linuxserver/docker-mods/tree/universal-package-install
This is not a change we will include in our image.
